### ISSUE TITLE
[bug] microsplat procedural also required #if __MICROSPLAT__

### ISSUE THREAD

**Issue by twobob** [xshazwar/mountains-beyond-mountains#10]
**Describe the bug**
installing microsplat gives Assets\billboards\MicroSplatPlugin\Integration\MSProceduralRules.cs(13,16): error CS0246: The type or namespace name 'MicroSplatProceduralTextureConfig' could not be found (are you missing a using directive or an assembly reference?)

**To Reproduce**
Add microsplat plugin

**Expected behavior**
compile

forgot to post this before

**Comment by twobob** [comment]
![image](https://user-images.githubusercontent.com/915232/150135383-dff2eefb-fd85-4677-bda2-386fc8602cba.png)

**Comment by xshazwar** [comment]
Thanks for the report! MicroSplatProceduralTextureConfig is a Microsplat class. Maybe you need an asmref to solve this in the short term?

Take a look at the WIP GH-9. Among other things I've split things into separate asmdef libraries to try and solve this dependency issue with external libraries. The setup is quite different than the mainline though so I need to get some doc together (and a sample) before I merge it. Hopefully this weekend.

**Comment by twobob** [comment]
yeah. The procedural module maybe I dont have? don't recall having that if its an "extra"

**Comment by xshazwar** [comment]
Addressed in #9
